# Generated by Django 4.2.6 on 2023-10-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nuson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai1', models.FloatField()),
                ('nilai2', models.FloatField()),
                ('nilai3', models.FloatField()),
                ('nilai4', models.FloatField()),
                ('nilai5', models.FloatField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
