# Generated by Django 4.2.6 on 2023-10-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuson',
            name='deviceName',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuson',
            name='nilai1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nuson',
            name='nilai2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nuson',
            name='nilai3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nuson',
            name='nilai4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nuson',
            name='nilai5',
            field=models.IntegerField(),
        ),
    ]
